name: release

# Only do the release on x.y.z tags.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

# We need this to be able to create releases.
permissions:
  contents: write

jobs:
  # The create-release job runs purely to initialize the GitHub release itself,
  # and names the release after the `x.y.z` tag that was pushed. It's separate
  # from building the release so that we only create the release once.
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the release version from the tag
        if: env.VERSION == ''
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Show the version
        run: echo "Version:" $VERSION

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $VERSION --draft --verify-tag --title "nixfetch $VERSION"

    outputs:
      version: ${{ env.VERSION }}

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x86_64-linux
            package: .#packages.x86_64-linux.default
          - name: aarch64-linux
            package: .#packages.aarch64-linux.default

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Build ${{ matrix.name }} binary
        run: nix build ${{ matrix.package }}

      - name: Copy binary
        run: cp result/bin/nixfetch nixfetch-${{ matrix.name }}

      - uses: actions/upload-artifact@v4
        with:
          name: nixfetch-${{ matrix.name }}
          path: nixfetch-${{ matrix.name }}

  upload-release:
    name: upload-release
    needs: ['create-release', 'build-release']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Upload release binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          version="${{ needs.create-release.outputs.version }}"
          gh release upload "$version" artifacts/*
